apiVersion: v1
kind: Service
metadata:
  name: nginx-service-clusterip
spec:
  ports:
    # the port that this service should serve on
  - port: 8001
    targetPort: 80
    protocol: TCP
  selector:
    name: nginx
